### ISSUE TITLE
What's going on under the hood

### ISSUE THREAD

**Issue by sio** [metamoof/powershell-powerbidesktop#3]
Hello,

It's great that you have started this project, a command-line interface for the Power Query engine would be of great use to many people.

Could you please explain how does it work?

Here is what I've been able to understand (or guess - my PowerShell skills are almost none):

- PowerBI Desktop internally runs a local instance of Analysis Services Server (an undocumented[?] and/or unsupported[?] feature)
- You detect the port that server is listening on
- You connect to that port with ADOMD - a .NET library for SSAS interaction. Do you invoke it as a .NET object or as a COM object?
- You execute DAX queries to retrieve the data sets. Or is it some dialect of SQL? Does that limit us to read-only access to the data model?

Please correct/expand my guesses. Thank you!

**Comment by metamoof** [comment]
Hi @sio, great to see you here!

So, I'm still relatively new with powershell, but I'm giving it a go for another project of mine - [lapsang](https://github.com/metamoof/lapsang) - where, with a friend who does know it a lot better, we're trying to do some Active Directory Auditing. (Don't bother looking at the repository right now, there's not much there!)

This particular spinoff project is aiming in the long run, as you might have guessed, at giving enough infrastructure for unit testing. 

Microsoft have stated, in passing, in some documentation, that Power BI is based on Analysis services, though they're very careful to try and separate the two. As far as I can tell, the Power BI modelling and reporting is heavily based on Analysis services, though I suspect they want the freedom to diverge in the long run, which is why they haven't documented how to connect to the backend.

As such, this Powershell module is wholly based on guesswork and poking around, and thoroughly unsupported by Microsoft. What follows below is mostly from trying to beat my head against it to make sense.

That being said, there's now an official [Power BI Powershell cmdlet set](https://github.com/Microsoft/powerbi-powershell) that only connects to the Online version of Power BI, and seems to be aimed at management, it doesn't seem to allow you to actually query the data in any way. You can, however, [connect to the data model using Excel](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel) which downloads a .odc file, which when examined shows that you connect to Power BI using the same adapters as analysis services.

Several people in the past have tried to connect to Power BI Desktop. I'm drawing inspiration from [this thread on the power BI forums](https://community.powerbi.com/t5/Desktop/Storing-and-using-information-from-a-dynamic-data-source-using/td-p/207293/page/2) and from the [PowerBIPS and PowerBIPS.Tools powershell modules](https://github.com/DevScope/powerbi-powershell-modules) which I am cribbing off heavily, but I've also googled the issue extensively.

As far as I can tell, Power BI is reusing parts of analysis services for the non-query-editor part. DAX is a long-established language, and actively supported, so it makes sense. They've then cobbled on what they call the Mashup Engine to the backend, which seems to be the bit that runs PowerQuery. 

Power BI Desktop actually spins up an analysis services frontend per PBIX file on its own unprivileged port. So the first problem is determining how to connect to these frontends. The two methods I've found online, so far, are to query a file called `msmdsrv.port.txt` which is stored in a temporary directory somewhere under `%UserProfile%\Microsoft\`, or the slightly more user-friendly method of querying the power BI process, and seeing what ports that process is connecting to on localhost. This is what the `Get-PowerBiDesktopConnection` command does. 

The meat of the Powershell module is `Invoke-PowerBIDesktopCommand` which uses [the ADOMD.NET client](https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models-adomd-net-client/adomd-net-client-functionality?view=sql-server-2017) to connect to the server. As this is Powershell, it uses the native .NET Managed libraries, specifically the [`Microsoft.AnalysisServices.AdomdClient` namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.adomdclient).

The question is, now, what commands to use. The documentation is vague, saying only that it accepts [MDX](https://docs.microsoft.com/en-us/sql/mdx/multidimensional-expressions-mdx-reference), and ["XMLA-Compliant"](https://docs.microsoft.com/en-us/sql/analysis-services/xmla/xml-for-analysis-xmla-reference) commands. `Get-PowerBIDesktopTables` uses a `SELECT` command against what is a [Dynamic Management View](https://docs.microsoft.com/en-us/sql/analysis-services/instances/use-dynamic-management-views-dmvs-to-monitor-analysis-services), and assume that this is the [MDX `SELECT` statement](https://docs.microsoft.com/en-us/sql/mdx/mdx-data-manipulation-select?view=sql-server-2017) rather then the SQL one. I basically cribbed this off the [`Export-PBIDesktopToCSV` command in PowerBIPS.Tools.](https://github.com/DevScope/powerbi-powershell-modules/blob/master/Modules/PowerBIPS.Tools/PowerBIPS.Tools.psm1#L272)

`Read-PowerBIDesktopTable` uses an `EVALUATE` command, which as far as I can tell is neither MDX nor strict XMLA, but rather DAX. I have yet to play with it much, but I'm going to try and see if I can do more DAX commands with this invocation method. As you can tell, I'm still playing around.

I'm also going to add a command to force Power BI to refresh tables. This I have seen being done using the [AMO connector](https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models/analysis-management-objects/developing-with-analysis-management-objects-amo) rather than the ADODB.NET connector. [#4]

Next on my list is seeing if I can affect the underlying model, the PowerQuery layer if you will. I've taken a peek at the Power BI model using SQL Server Management Studio, and found that there is one connection per M query, and that there appears to be a zip file that defines that query in the connection string definition. PowerBIPS.Tools [already has a function for extracting M from the connection,](https://github.com/DevScope/powerbi-powershell-modules/blob/master/Modules/PowerBIPS.Tools/PowerBIPS.Tools.psm1#L648) which looks useful to at least validate that what we're running is what's on disk elsewhere, but I'm unsure if we can actually modify that in order to modify the query in the substrate, it will take some experimenting, and, to be honest, I'm sot sure if this would be a step too far, given it's thoroughly undocumented. [#5, #6, #10]

Another thing I want to do is check whether I can mark a table as Hidden. These tables are queryable through DAX and SMSS, but don't appear in the Power BI Desktop interface. As such, it'd be interesting if we could define PowerQuery Unit Test outputs as a table Query that we can then hide using a cmdlet, and extract the Unit Test results using a refresh of that table using Powershell, and write them to a Test result file.[#9] What I'm pretty confident can be done is comparing the result of a query to that of an external CSV file using PowerShell, to validate the query result modifying an input. I'm yet to see if this is useful in a real world scenario, though. [#6]

I hope this gives you enough information as to what is happening behind the scenes. I took the opportunity to dump a lot of my thoughts, and I will probably reformat this as documentation in the wiki, as well as maybe generate a few issues out of it. Feel free to ask any more questions!

**Comment by metamoof** [comment]
I've updated this last comment with links to the issues I've created to document these tasks.

**Comment by metamoof** [comment]
I realise I haven't answered one of your questions: I don't know if we are limited to read-only access to the data model. 

I suspect we can probably quite easily add calculated columns and tables to the system using a little DAX, but I'm not sure I see much use for that, other than for temporary testing. I don't know if we can affect the model substrate directly, though, unless I can find a way to either call an M function from DAX or XMLA or modify a query parameter from DAX or XMLA. 

I've opened a couple of research issues to look into that: #10 #11

**Comment by sio** [comment]
Thank you very much! Your response was very detailed and thorough, and I
believe it can be a valuable addition to the project wiki.

>
You've mentioned Microsoft PowerShell cmdlets for PowerBI online - I fear
they will be of no help to you with this project. From what I've seen they
just wrap up the functionality of PowerBI REST API and do not offer
anything useful for Desktop users.
